https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - statdist
  restart: always
  environment:
    DOMAINS: 'statdist.ksmzn.com -> http://statdist:3838'
    STAGE: 'production'
    # FORCE_RENEW: 'true'

statdist:
  build: .
